name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./ci/sys-dep-install.sh
    - name: build
      run: mkdir build && cd build 
    - name: cmake
      run: cmake -DCAMKE_BUILD_TYPE=Release ..
    - name: make
      run: make -j2
    - name: test
      run: ../bin/epictest
