name: C/C++ CI

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Install build tools
      run: |
        sudo apt-get install autoconf libtool pkg-config libgmp-dev
        sudo apt-get autoremove
    - name: Install gcc8
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt-get install gcc-8 g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
        gcc -v
        g++ -v
    - name: Install clang-9
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt-get update
        sudo apt-get install clang-9
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 100
        clang -v
        clang++ -v
    - uses: actions/checkout@v1
    - name: Install cmake 
      run: cd ci && ./install-cmake.sh
    - name: Install openssl 
      run: cd ci && ./install-openssl.sh
    - name: Install protobuf
      run: cd ci && ./install-protobuf.sh
    - name: Install grpc
      run: cd ci && ./install-grpc.sh
    - name: Install rocksdb
      run: cd ci && ./install-rocksdb.sh
    - name: Install secp256k1
      run: cd ci && ./install-secp256k1.sh
    - name: Install libevent
      run: cd ci && ./install-libevent.sh
    - name: Install googletest
      run: cd ci && ./install-googletest.sh

    - name: cmake
      run: mkdir build && cd build && cmake -DCAMKE_BUILD_TYPE=Release ..
    - name: make
      run: cd build && make -j2
    - name: Run epic test
      run: ./bin/epictest

  test-macOS:
    runs-on: [macos-latest]
    steps:
    - name: install brew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: install via brew
      run: |
        brew update && brew upgrade && brew cleanup
        brew install autoconf automake # libtool
        brew install openssl@1.1
        export OPENSSL_ROOT_DIR="/usr/local/opt/openssl@1.1"
        # brew install cmake 
        brew install gmp 
        brew install grpc 
        brew install rocksdb 
        brew install protobuf
    - uses: actions/checkout@v1
    - name: Install secp256k1
      run: cd ci && ./install-secp256k1.sh
    - name: Install libevent
      run: cd ci && ./install-libevent.sh
    - name: Install googletest
      run: cd ci && ./install-googletest.sh

    - name: cmake
      run: mkdir build && cd build && cmake -DCAMKE_BUILD_TYPE=Release ..
    - name: make
      run: cd build && make -j2
    - name: Run epic test
      run: ./bin/epictest

